lobal:
  network: testnet
  service:
    ports:
      rpc: 18332
memory:
  requests: 128Mi
  limits: 1024Mi
persistence:
  enabled: true
  size: 30Gi
service:
  ports:
    p2p: 18333
labels:
  kube-monkey/enabled: enabled
  kube-monkey/identifier: bitcoind
  kube-monkey/kill-mode: fixed
  kube-monkey/kill-value: "1"
  kube-monkey/mtbf: "8"
podLabels:
  kube-monkey/enabled: enabled
  kube-monkey/identifier: bitcoind
specter:
  enabled: false
